dist: xenial
language: node_js
node_js:
  - lts/*
  - node
install:
  - npm install
  - curl -o /tmp/archivist.tgz https://github.com/stellar/go/releases/download/snapshots/stellar-archivist-snapshot-linux-amd64.tar.gz && cd /tmp && gunzip archivist.tgz
cache:
  directories:
    - node_modules
script:
  - npm test
