dist: xenial
language: node_js
node_js:
  - lts/*
  - node
install:
  - npm install
  - curl -L -o /tmp/archivist.tgz https://github.com/stellar/go/releases/download/snapshots/stellar-archivist-snapshot-linux-amd64.tar.gz && cd /tmp && tar xf archivist.tgz && cd -
cache: npm
script:
  - npm test
